### ISSUE TITLE
Could not convert a Qwen2.5 finetuned into torch.

### ISSUE THREAD

**Issue by sorasoras** [chu-tianxiang/llama-cpp-torch#3]
```
PS W:\windows_cuda\llama-cpp-torch> python convert.py --input .\sakura-14b-qwen2.5-v1.0-iq4xs.gguf --output .\Output\
Traceback (most recent call last):
  File "W:\windows_cuda\llama-cpp-torch\convert.py", line 6, in <module>
    from sentencepiece import sentencepiece_model_pb2
  File "C:\Users\shing\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentencepiece\sentencepiece_model_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ModuleNotFoundError: No module named 'google'
```
I do not kow that this google module, but I guess this is related to sentencepiece

**Comment by ofer-tal** [comment]
I ran into the same problem today.
solved with 
pip install --upgrade google-api-python-client

**Comment by webbrain-one** [comment]
Hi @shing, thanks for the report! I’ve opened #5 to fix this by adding the missing `protobuf` dependency so `sentencepiece` can import correctly. That should resolve the `No module named 'google'` error and let the conversion run.
